# **Quiz 1 - Python NumPy**
---
This quiz will help you practice the skills coding in Python and using Numpy.

> **Note:** This aquiz will be graded on **UNCode** **[https://uncode.unal.edu.co/](https://uncode.unal.edu.co/)** ([doumentation](https://juezun.github.io/)). In each exercise is indicated where you should write your code. Complete the code, download the file submit it in **UNCode**.

In [ ]:
!python --version
import numpy as np

print('NumPy', np.__version__)

Python 3.8.10
NumPy 1.22.4


This quiz was created originaly in:

- Python 3.6.9

- NumPy: 1.19.5

## **1. *FizzBuzz*  - Python**

**Solution**

In [ ]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.
def FizzBuzz(x):
    answer =""
    if x % 3 == 0 and x % 5 == 0:
      answer = "FizzBuzz!"
    elif x % 3 == 0:
      answer = "Fizz!"
    elif x % 5 == 0:
      answer = "Buzz!"
    else:
      answer = "..."
    return answer


<details>    
<summary>
    <font size="3" color="darkgreen"><b>Verification cases </b></font>
</summary>


## **2. *FizzBuzzList*  - Python**
---

Write the function *FizzBuzzList* that returns a list with the answers of *FizzBuzz* for the integer numbers $1$ to $n$ (including $n$).

**Solution**

In [ ]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.
def FizzBuzzList(n):
    ans = []
    if n < 0:
      return ans
    for i in range(1,n+1):
      answer =""
      if i % 3 == 0 and i % 5 == 0:
        answer = "FizzBuzz!"
      elif i % 3 == 0:
        answer = "Fizz!"
      elif i % 5 == 0:
        answer = "Buzz!"
      else:
        answer = "..."
      ans.append(answer)
    return ans

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Verification cases </b></font>
</summary>

## **3. *Standarize* - z scores - NumPy**

**IMPORTANT:** Solve this exercise using the ***`NumPy`*** functions ***`mean`*** and ***`std`*** not using prograrmming structures like ***`if`*** or ***`for`***.

In [ ]:
import numpy as np

X = np.array([1.2,3.2,4.3,5.6])
print(X.mean())
print(X.std())

3.5749999999999997
1.6130328576938535


**Solution**

In [ ]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.

import numpy as np

def standarize(X):
  X_standarized = (X - np.mean(X))/np.std(X)
  return X_standarized

## **4. *Main diagonal matrix*  - NumPy**

**IMPORTANT:** Solve this exercise using the ***`NumPy`*** function ***`diag`***  and ***`astype`*** not using prograrmming structures like ***`if`*** or ***`for`***.

In [ ]:
import numpy as np
A = np.array([
    [1, 0, 2, 9, 2],
    [9, 2, 6, 5, 7],
    [6, 4, 3, 4, 7]
    
])

print(A.astype(float))

print(np.diag(A))

print(np.diag(np.diag(A)))

[[1. 0. 2. 9. 2.]
 [9. 2. 6. 5. 7.]
 [6. 4. 3. 4. 7.]]
[1 2 3]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [ ]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.

import numpy as np

def main_diagonal_matrix(A):
  D = np.diag(np.diag(A)).astype(float)
  return D

**¡Congratulations!** You have finished your first quiz.



## **Credits**
Created by 
  - German Hernandez
  - Oscar Fabian Sierra Daza
  
Modifying quizzes originaly created by
  - Felipe Restrepo Calle
  - Alberto Nicolai Romero Martínez
  - Miguel Angel Ortiz Marín
